services:
  - type: web
    name: inshop-site
    env: node
    buildCommand: npm install && npm run build
    startCommand: node_modules/.bin/next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
